apiVersion: clouddeploy.googleapis.com/v1
kind: DeliveryPipeline
metadata:
  name: apnr-Server-pipeline
description: CI/CD Pipeline for APNR Server
serialPipeline:
  stages:
    - targetId: dev
      profiles:
        - deployment-profile
      strategy:
        standard:
          verify: false
    - targetId: staging
      profiles:
        - deployment-profile
      strategy:
        standard:
          verify: false
    - targetId: prod
      profiles:
        - deployment-profile
      strategy:
        standard:
          verify: true
